# Ansible Playbook
# git-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - Git
  hosts: ubi
  become: true
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
    # securedevcontainer_variant is a group variable; see hosts.yml
    - _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
...